baseURL = 'https://claridelune.com/'
languageCode = 'es'
title = 'claridelune.com'
theme = 'archie-claridelune-theme'

copyright = "© claridelune"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/claridelune"

[[params.social]]
name = "Mastodon"
icon = "simple:mastodon"
url = "https://social.vivaldi.net/@claridelune"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/claridelune"

[[menu.main]]
name = "/home"
url = "/"
weight = 1

[[menu.main]]
name = "/posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "/now"
url = "/now"
weight = 3

[[menu.main]]
name = "/tags"
url = "/tags"
weight = 4
