baseURL = 'https://claridelune.com/'
title = 'claridelune website'
theme = 'claridelune-theme'

[languages]
	[languages.en]
		label = 'English'
		locale = 'en-US'
		title = 'claridelune website'
		weight = 1
	[languages.es]
		label = 'Español'
		locale = 'es-PE'
		title = 'claridelune website'
		weight = 2

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
