baseURL = 'https://claridelune.com/'
languageCode = 'es'
title = 'Claridelune Site'
theme = 'archie-claridelune-theme'

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/claridelune"

[[params.social]]
name = "Mastodon"
icon = "simple:mastodon"
url = "https://social.vivaldi.net/@claridelune"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/claridelune"

